version: '3.8'
services:
  backend:
    build: .
    container_name: lemming_backend
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    image: nginx:alpine
    container_name: lemming_cockpit
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    depends_on:
      - backend
